### ISSUE TITLE
Add more details on funding status: monthly/yearly income, expenses

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#102]
We have a Patreon widget showing the current status of the Patreon crowdfunding (albeit it's down right now until we port to PHP7, cf. #95).

We need to expand this to show donations that we get from other sources (direct sponsorship, Paypal donation, grants/awards), and also give information on how we use this money.

This could go to the Donate page, or to a dedicated page.

See https://www.reddit.com/r/godot/comments/dxm8sj/concerns_about_godots_crowdfunding_transparency/f7tgxxy?utm_source=share&utm_medium=web2x

**Comment by nikhilCad** [comment]
Any updates on this?

**Comment by phantomdesvin** [comment]
With the recent generous grant from Epic, this could be a good moment to work on the lack of transparency.

**Comment by magikmw** [comment]
@akien-mga Is there any way someone outside the core team could help? If we had more info on this, some mvp or 'done definition' perhaps this issue would move forward faster.

**Comment by nikhilCad** [comment]
@akien-mga  please give this issue high priority, transparency is the second thing one looks in open source projects (first one being the features of the project). I believe a dedicated page is the way to go.

**Comment by Calinou** [comment]
@magikmw @nikhilCad Unfortunately, getting this information in the first place is proving difficult for them. From what I've heard, the Software Freedom Conservancy handles direct donations, which makes it difficult to know how much money was exactly received. I'm not involved in the project leadership committee, so I can't help them do that.

It may take a while for this to be resolved.

**Comment by nikhilCad** [comment]
Can't the donations from corporations be hardcoded, and donations from patrons counted by their api, and then just showing the sum on the website?

**Comment by Calinou** [comment]
@nikhilCad The issue is that they're not always constant. Some of them can come and go quickly. I had precisely that idea as well, but I don't think it can be made to work reliably.

**Comment by clayjohn** [comment]
We finally have a proper funding page! https://fund.godotengine.org/

We have discussed between Foundation board members and we don't think we can show expenses on a monthly level of granularity. As a not-for-profit we are obligated to publish yearly audited financial statements (prepared by an accountant). We don't feel comfortable presenting non-audited expenses to the public, especially if there is a chance that our monthly statements don't align with the audited statements (because we are not accountants and may easily make a mistake). 

That being said, we are taking steps to provide more transparency now that we have the Foundation. For starters, we will start to post more information on the blog like [our recent post on funding and hiring](https://godotengine.org/article/funding-breakdown-and-hiring-process/). And soon we will post summaries of the current [audited financial statements](https://sfconservancy.org/about/transparency/) (prepared by the SFC).

Accordingly, I will go ahead and close this issue as implemented
