### ISSUE TITLE
Add torrent downloads as an alternative to direct downloads to workaround slow downloads

### ISSUE THREAD

**Issue by CyberFoxHax** [godotengine/godot-website#105]
downloads.tuxfamily.org works fast for some. I for one am looking at sub 20kb/s. (Maybe it's related to geography?)

Godot is not a big package, but the targeting packs however are. I have attempted to download it for 2 days now, and failed.

Should you decide to go with it then I'd be delighted to seed.

**Comment by Calinou** [comment]
It'd be nice to have, but it adds one extra step to the releasing process which is already quite lengthy. I have no control over it, so I can't do it myself. [mktorrent](https://github.com/Rudde/mktorrent) can be used to create `.torrent` files automatically. Additionally, the downloads on TuxFamily can be referenced as "web seed" URLs in the `.torrent` files, so that the files can still be downloaded even if nobody is seeding them (just in case).

> downloads.tuxfamily.org works fast for some. I for one am looking at sub 20kb/s. (Maybe it's related to geography?)

Feel free to use my mirror in the meantime: https://archive.hugo.pro/godot-tuxfamily/

**Comment by CyberFoxHax** [comment]
I actually managed to download it using an accelerator (10 pieces). Not that i consider it a sustainable solution.

**Comment by Xananax** [comment]
To weigh in: I transit through several countries with regular internet (which I will contrast with "fast internet" that you get in Western Europe), mainly in the Middle East & Eastern Europe. I'm used to very slow, spotty, or intermittent connections. I know, from discussing with people, that my speeds are comparable to those of people in rural areas, even in developed countries.  
I call it "regular internet" rather than "slow internet" because, outside of Western Europe, or even cities in Western Europe, the general experience of a connection is not so great.

My experience:  
More often than not, the export templates are simply undownloadable for me, and I have to send my binary to a friend to do the exports for me. Sometimes, a bit like @CyberFoxHax describes, I download the export templates on a VPS, set up syncthing, and let them sync back slowly to my local computer. It works, but not everyone has a VPS and the means to use it.

I had not even thought of complaining about this because I, like everyone else in that situation, have gotten so used to the Internet in general not giving a care about making us download 50m webpages that we just shrug and work around it. But for sure, having torrents would be a big relief.

**Comment by Wavesonics** [comment]
Just to second what @Xananax said, I am mostly on cellular data in rural areas. Beyond speed issues, the connections regularly drop out, so the fact that the current in-engine downloader can't resume a dropped connections means lots of broken downloads requiring a full re-download.

So in addition to more speed, a torrent for them would mean a much more durable download processes, allowing easily for dropped connections to resume where they left off.

**Comment by ShalokShalom** [comment]
https://mirror.math.princeton.edu

Princeton University is pretty gracious when it comes to hosting
Their IT department pretty much collects Linux distros

**Comment by akien-mga** [comment]
For those experiencing slow downloads in a reliable manner, can you send me (`remi@godotengine.org`) -- if you don't mind -- information about your geographical location and ISP? I would pass it on to TuxFamily admins to debug why you might be getting such a slow (likely far away) mirror.

**Comment by swedneck** [comment]
I'd like to suggest considering IPFS downloads as well, i already mirror a snapshot of the tuxfamily downloads at https://godot.swedneck.xyz and you can do much the same thing as torrent webseeds with IPFS as well.

**Comment by swedneck** [comment]
Oh and i should also note that with IPFS you can set up collaborative clusters, which enables new releases to be automatically pinned by those who wish to always seed the latest files.
https://cluster.ipfs.io/documentation/collaborative/

**Comment by troys-code** [comment]
Is there anything blocking this? I would sponsor it if that's helpful

**Comment by Calinou** [comment]
> Is there anything blocking this? I would sponsor it if that's helpful

There is nothing blocking this, but I don't control the release process itself and Akien doesn't have time to look into this.

**Comment by troys-code** [comment]
@akien-mga when you have time, can you briefly explain how the website is deployed? It's not clear to everyone how changes make it to the live site.

**Comment by Calinou** [comment]
> when you have time, can you briefly explain how the website is deployed? It's not clear to everyone how changes make it to the live site.

Changes are deployed by pushing commits to this repository, SSHing to TuxFamily's servers and running `git pull` there.

However, binary files are uploaded to https://downloads.tuxfamily.org/godotengine/ instead (and are linked to from the website). Official releases are compiled using [build containers](https://github.com/godotengine/build-containers) which would have to be modified to *optionally* call something like mktorrent.

See also https://github.com/godotengine/godot-docs/issues/4202.

**Comment by Calinou** [comment]
[A GitHub Releases mirror has been added](https://github.com/godotengine/godot-website/pull/360), making torrent downloads not really relevant to propose anymore. Closing.

**Comment by Phixygamer** [comment]
I created torrent files that the community can seed or distribute to improve download speed and reliability. 
Given this is an open source project and people are still having this issue we don't need the godot foundation itself to create the torrents just a semi-official space where we can share torrents that the community verifies match the originals.
[https://phixy.eu/godot-export-template-torrent/](https://phixy.eu/godot-export-template-torrent/)
