### ISSUE TITLE
QA: 3.0 vs 2.x

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot-website#14]
There are thousands of threads on the Q&A website that are about Godot 2.0.
But once 3.0 gets widely used, there will be a hard time to find answer about 2.x series or 3.x series, since it's it's not explicit which posts concerns one or the other, unless added in a comment. Some questions have the `godot2` or `godot3` tags, but they are only about 20.

Do we need to do something about Q&A for 3.0?

**Comment by alketii** [comment]
Very good point.
Maybe we should do a SQL query and tag all of them, then manually remove the ones which are for 3.0 ?

**Comment by cbscribe** [comment]
Revisiting this one. Lots of 2.1 vs 3.0 confusion in help requests these days.

The problem with tags is because they're freeform, all of the following appear as suggestions when you start typing:`godot3-0 godot godot3 godot2`

I think it might be best if there were a dropdown for choosing the version (before long we'll need to add 3.1).

Per akien's suggestion, we should probably revisit the category list as well.

**Comment by Calinou** [comment]
> Maybe we should do a SQL query and tag all of them, then manually remove the ones which are for 3.0 ?

Replacing tags manually is the only solution I can foresee right now, given that [Question2Answer is mostly unmaintained by now](https://github.com/q2a/question2answer).

**Comment by Calinou** [comment]
Question2Answer provides an optional extra field. I've just added it:

![Ask a question](https://user-images.githubusercontent.com/180032/101928376-cbe83e00-3bd5-11eb-8466-39aaf903ba5b.png)

I also added a notice to remind the user to use the Search feature before asking a question.
