### ISSUE TITLE
Blog post banners became smaller

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#177]
**Operating system, Browser, Browser Version:**
Linux, Firefox Nightly from today

**Issue description:**
After recent changes to the CSS of blog posts, the banner image seems to have become smaller than it used to be:
- the text area is wider, so that's partly expected
- but the width of the banner seems to be less than it used to be (I remember something around 700+ px?)

CC @pycbouh @Calinou 

**Screenshots (greatly appreciated if it’s a style issue)**
![Screenshot_20200917_152538](https://user-images.githubusercontent.com/4701338/93476403-0c4b5f00-f8fa-11ea-8120-369d507516d9.png)

**Comment by akien-mga** [comment]
Here's how it used to be (from archive.org):
![Screenshot_20200917_152709](https://user-images.githubusercontent.com/4701338/93476604-4a488300-f8fa-11ea-971a-e607925d3981.png)

So it was 720p wide, now it seems to be 590p. I think 720p was good.

**Comment by YuriSizov** [comment]
This was changed with #164. Due to width adjustments to the body the title image became too big, so I limited it. Because images used there tend to have different dimensions I limited it at 70% which gives you 588px on that particular entry.

We can change it to 720px or ~85% which would be approximately the same for this image. What should be considered is the level at which the text is displayed initially. Your screencap of Archive.org gives a perfect example of disproportionate relation between the image and the content (in my opinion, at least). Though from quick testing 720px is not that different from 70% in the current layout, so it would be fine in my book:

[70%](https://user-images.githubusercontent.com/11782833/93477845-2b4eee80-f904-11ea-8b1c-873e3c708aaf.png)
[720px](https://user-images.githubusercontent.com/11782833/93477618-eb880700-f903-11ea-8c42-7fa01c44b3eb.png)

It should only take changing this one line:
https://github.com/godotengine/godot-website/blob/b98ec49676fa8ce6f16385b6d612975bf8c389e0/themes/godotengine/layouts/article.htm#L59

I'm currently neck-deep into changes for internationalization, so if somebody else can make a PR, go ahead.

**Comment by akien-mga** [comment]
AFAIK the image width was constant, at least it was always 720px for me on a 1920x1080 display, even when resizing the window - at least as long as it used the "desktop" menu bar and not the "mobile" one. When resizing further down / for mobile devices, it would then be scaled further down indeed.

Using a percentage is fine with me but it would be good if it kept a constant width for the desktop/wide enough style, so that pictures can be designed in a way that will resize nicely (e.g. a pixel art screenshot in 1440px wide would scale well to the fixed 720px). If it then scales to non-even ratios for mobile or very narrow windows, that's acceptable.

**Comment by akien-mga** [comment]
I pushed daea2ca to make it wider with 85% for now. Let's see if there's a better design that we can use to fully close this or if we consider that it's good as is.

**Comment by YuriSizov** [comment]
I guess my argument doesn't make much sense because we are talking about width. It would make sense to talk about the different dimensions if we were limiting the height by its percent, not the width. But for the width it is going to be constant. Used to be 100% of the maximum width and now it's 70%, but in practice it means fixed width because the maximum width is constant. 🙃 

So anyway, 720px is acceptable if we keep the height in check when creating images for the articles. In the 3.2.3 news we have two full paragraphs of text, which is good.

**Comment by akien-mga** [comment]
Since we didn't revisit this in a year, I guess we're fine with the current design :)
