### ISSUE TITLE
Add homepage section for company sponsors

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#2]
Our [Patreon campaign](https://www.patreon.com/godotengine) includes Gold and Platinum sponsorship levels (intended mainly for companies), for which we promise to put company logo (and I guess, a link when you click on the logo) on the homepage.

We should add a horizontal section for that below the "Get involved" section and before the footer:
![image](https://user-images.githubusercontent.com/4701338/30325305-88926a4e-97c4-11e7-8158-cdcdf9bc34aa.png)

I guess it could be two columns, with Platinum sponsors on the left and Gold sponsors on the right, and with a link to the [Donate](https://godotengine.org/donate) page to learn more about sponsoring the project or just supporting it financially. (I still need to write some details about the sponsoring deals on that page, but you can link to it anyway).

Currently we have one Gold sponsor, [Gamblify](https://gamblify.com/), so their logo should be added: 
[Gamblify_Logo_2_Colors.zip](https://github.com/godotengine/website/files/1295877/Gamblify_Logo_2_Colors.zip)

**Comment by pcvonz** [comment]
The svg you linked doesn't seem to be the same one that appears on their website. Appears it was exported from illustrator, which I guess doesn't have the best svg exporter?
_![logo_compare](https://user-images.githubusercontent.com/6378569/30714059-4e8aeb9c-9ec6-11e7-8a77-56440e42cc6a.png)_


This seems to be a pretty standard layout when it comes to mentioning sponsors:

![sponsor_mockup](https://user-images.githubusercontent.com/6378569/30714520-f2f15d0a-9ec7-11e7-9086-de5159d8fbe7.png)

The Patreon campaign says that "Mini Sponsors" will also have their names featured on the website. Since it seems to be relatively cheap, I'm guessing that there will be more of them. We can leave out Platinum and mini if we don't have any yet and add the sections when we do or keep it there to encourage more companies to sign up.

**Comment by akien-mga** [comment]
For "Mini Sponsors" we do mention that they will be featured on the website, but not on the landing page. We'll likely add a "Sponsors" page, or add them to the "Donate" page - the Platinum and Gold sponsors would also be featured there + on the landing page.

**Comment by pcvonz** [comment]
I kind of like the idea of including them on the landing page. Look how [Webpack](https://webpack.js.org/) handles them.

**Comment by akien-mga** [comment]
Regarding the logo, I guess you can use the PNG directly; if there's a need for a different resolution or SVG, we can see with Gamblify to have a better version.

**Comment by akien-mga** [comment]
Fixed by fd0612fe5b.

**Comment by akien-mga** [comment]
We now have a second Gold sponsor to add to the homepage, GameDev.tv! \o/
- [Logo](https://discourse-cdn-sjc1.com/business2/uploads/gamedev/optimized/1X/2d1f1721ff9a04b33e75ce2e606e124626104249_1_690x149.png)
- [Website](https://gamedev.tv/)
