### ISSUE TITLE
On Firefox 83, the showcase thumbnails are squashed

### ISSUE THREAD

**Issue by dsnopek** [godotengine/godot-website#207]
**Operating system, Browser, Browser Version:**

Ubuntu 18.04
Firefox 83.0

**Issue description:**

On this page:

https://godotengine.org/showcase

The showcase thumbnails are squashed down to basically the height of 2 lines of text (see screenshot below).

In Chrome (on the same machine), the thumbnails are normal sized, and match the screenshot on in [this news article](https://godotengine.org/article/new-showcase-for-projects-made-with-godot).

Relates to PR https://github.com/godotengine/godot-website/pull/199

**Screenshots (greatly appreciated if it’s a style issue)**

![Selection_195](https://user-images.githubusercontent.com/191561/101384518-27d26000-3880-11eb-9bc9-d3b25aea7653.png)

**Comment by Calinou** [comment]
Clear the cache while refreshing (<kbd>Ctrl + F5</kbd>) to solve the issue. Something must be wrong in the web server configuration; we should reduce static files' client-side caching duration.

(October doesn't have built-in support for versioning/cache busting assets, and we don't want to use a build pipeline for simplicity reasons. We used one in the past and it kept confusing new contributors, since most of them aren't web developers by trade.)

**Comment by dsnopek** [comment]
Ah, ok! Clearing the cache fixed it for me
