### ISSUE TITLE
Add tentative license compliance instructions on the License page

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-website#46]
As suggested [on reddit](https://www.reddit.com/r/godot/comments/83hxet/question_about_godot_licence_terms/), it would be a good idea to display further instructions on how to comply with the MIT license for Godot projects on the License page. There should be a disclaimer as those instructions should not be considered legal advice.

Some third-party libraries also require displaying the license text as well (or even an attribution notice, in the case of Freetype).

**Comment by danielytics** [comment]
>Some third-party libraries also require displaying the license text as well (or even an attribution notice, in the case of Freetype).

It would be really useful to also link the [README from the thirdparty directory](https://github.com/godotengine/godot/blob/master/thirdparty/README.md) as it lists all of the third party libraries and their licenses. 
It would be even more useful to gather the licenses together on a single page, or even to compile a complete text containing the actual license text for each license ready to copy and paste for Godot users, but I guess that's too much to ask. A link to the README would be great, though!

**Comment by akien-mga** [comment]
>It would be even more useful to gather the licenses together on a single page, or even to compile a complete text containing the actual license text for each license ready to copy and paste for Godot users, but I guess that's too much to ask.

You mean this? :) https://github.com/godotengine/godot/blob/master/COPYRIGHT.txt

It's linked on the [License page](https://godotengine.org/license) of the website.

> As suggested on reddit, it would be a good idea to display further instructions on how to comply with the MIT license for Godot projects on the License page.

The page also includes general advice on how to credit the project and its license in games, encouraging people to link to this very page which contains the MIT license + a link to the COPYRIGHT.txt file with the license of all embedded components.

It's not 100% sufficient as it's a link to the COPYRIGHT.txt of the master branch, which is slightly different to that of the 2.1 branch for 2.1.x games for example. But it's a good first step.

To go further, I plan to add methods to the `Engine` singleton to get the Godot license text, and the complete dump of all license texts for all embedded libraries, so that people who want to do everything right by the licenses can do it easily.

> There should be a disclaimer as those instructions should not be considered legal advice.

Indeed. PR welcome to add that :)

**Comment by danielytics** [comment]
Oh wow, how did I miss that!? Good thing I haven’t shipped anything yet :) 

Adding methods to get the license text would be incredibly convenient too! 👍

**Comment by Calinou** [comment]
Now that we have a page about it in the documentation ([Complying with Licenses](https://docs.godotengine.org/en/latest/tutorials/legal/complying_with_licenses.html)), we should probably link to it on [godotengine.org/license](https://godotengine.org/license).
