### ISSUE TITLE
Center the images uses as article thumbnails

### ISSUE THREAD

**Issue by groud** [godotengine/godot-website#64]
In the [article list](https://godotengine.org/news), each thumbnail is basically a square subset of the top banner shown when you open the article. However, the square is taken from the left of the banner, which, in most case does not fit really well. Indeed, the most representative part of the banner is usually the center.

I suggest we use the center of the thumbnails instead of its left part as a thumbnail.

**Comment by Calinou** [comment]
It should be as easy as adding `background-position: center` to all article thumbnails (in the same class where `background-size: cover` is defined, I guess).

```css
background-position: center;
```

**Preview:**

![image](https://user-images.githubusercontent.com/180032/45753257-74d2a900-bc18-11e8-8a70-bbc7fc92584e.png)

**Comment by MHillier98** [comment]
This would be a good change for some banners, but for others, it would appear this has been used as a feature:

**Example 1:**
![image](https://user-images.githubusercontent.com/26564949/54475432-67a01b00-4845-11e9-9fea-6abf629d9638.png)

Changes to:
![image](https://user-images.githubusercontent.com/26564949/54475423-5951ff00-4845-11e9-8616-6f05a06221ae.png)

_However,_

**Example 2:**
![image](https://user-images.githubusercontent.com/26564949/54475441-82728f80-4845-11e9-898a-640377806879.png)

Changes to:
![image](https://user-images.githubusercontent.com/26564949/54475450-8c948e00-4845-11e9-9940-cf6f3c3ab01b.png)


This would have to be a change to how it's being used in function, or some edits would have to be made. Perhaps a better solution would be to add a preview image for blog posts? But that does seem like a fair bit of work to backfill images, and the added storage space for the images.

**Comment by akien-mga** [comment]
It wasn't really used as a feature, though you're right it turned out well in those two examples :)

If we change to center, I'll just keep this in mind when picking up banner images to ensure that the cropped version would look decent.

**Comment by MHillier98** [comment]
Another potential solution could be to make the images not take up the full height, allowing them to maintain their original size? However I do assume that it was designed to be a square originally:

![image](https://user-images.githubusercontent.com/26564949/54483941-88518a80-48b0-11e9-9f0b-6455e3df157e.png)

The CSS for the images:
```
element {
	background: url('https://godotengine.org/storage/app/uploads/public/5c7/67d/8c6/thumb_667_400x1_0_0_auto.png');
	background-position: center;
	background-repeat: no-repeat;
	background-size: contain;
}
```

**Comment by Calinou** [comment]
@MHillier98 I think that doesn't look as good from a visual standpoint, especially if images with different aspect ratios were to be used on the same page.

**Comment by MHillier98** [comment]
Agreed. Ultimately, this does come down to the images themselves. I do think it would be beneficial to standardize the sizing / formatting of the images put up there, but that potentially is a fair bit of work to go back and update images, if desired. I think this does come back to what the blog submitters want to do, as they are the ones actually entering the image.

However, a general rule that could be created for this would to always format the image so that either it's center or left side (how it currently is) would work as the thumbnail.

Again, I think the best examples of the problem can be seen in this screenshot:
![image](https://user-images.githubusercontent.com/26564949/54492688-d2705580-491c-11e9-8499-4acbe6bd4f53.png)

- The GDC meetup is a good example of what should be done (according to current styling), because the image itself is split into 2 sections
- The Summer of Code is a bad example of what should be done, because it cuts off nearly half the image
- The Beta 9 screenshot is an average example, as it's not a major problem showing that part of the game

IMO, the best solution to this would be separating out the blog banner image into a 2 images - a preview image (on the news page), and the banner (on the blog page), and making sure that the preview image is always a square. However, I think it comes back to the fact that the people submitting content are usually developers, not content managers or whatever they might be called to constantly be worrying about the website.

At the end of the day, this might even be a non-issue, but more of a reminder for the formatting of the images.

**Comment by groud** [comment]
My opinion in two points:
1) I think people won't like having to make two images to illustrate blog posts. IMHO, it's not worth asking for two image (but if it can be optional, than can be ok)
2) I think it is a lot easier to make a picture that works for both situations when the content is centered.

IMHO, centering the image is the way to go for now. Even if in some old pictures will not look right, this will simplify things in the future.

**Comment by jcs224** [comment]
In most news sites (coming from someone who worked at an online news publication at one point) the way this is done is by creating several different crops per image that are used wherever appropriate.

Like, a small thumbnail (square), a 16x9, a banner at the top of the article, and something for the news banner on the front page. These crops can actually be different images altogether, in the event that there isn't an appropriate thumbnail size, such as the above text-heavy images.

**Comment by Calinou** [comment]
@jcs224 While this is the best-looking solution, it also requires additional work (see @groud's comment above).

**Comment by ampsteric** [comment]
Please assign me this issue under hacktoberfest. , if it is still open.

**Comment by coppolaemilio** [comment]
> Please assign me this issue under hacktoberfest. , if it is still open.

@ampsteric We will opt-in repository-wide if we decide to participate this year, so please stop spamming.

**Comment by YuriSizov** [comment]
Solved with a redesign in https://github.com/godotengine/godot-website/pull/468.
