### ISSUE TITLE
Every qa page is leading to a 404

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-website#644]
For example, this URL: https://godotengine.org/qa/30988/i-cant-set-custom-size-to-an-object-when-instancing-gdscript
And any other URLs relating to qa from google.

However, if I reformat it as so: https://ask.godotengine.org/30988/i-cant-set-custom-size-to-an-object-when-instancing-gdscript, it will work and lead to the page.

The weird thing is, some pages linked like this on google DO in fact work, but then others (like the example provided) do not.

**Comment by Banderi** [comment]
~~I noticed this as well today, so I threw together a quick temporary redirect in JS. In case anyone is curious and/or can't be bothered to wait for a fix (probably won't be long), here's my script: https://openuserjs.org/scripts/Banderi/Godot_Forums_temp_redirect_fix~~

Edit: Seems like the problem is gone, indeed it was a very brief redirection issue.

**Comment by Calinou** [comment]
cc @coppolaemilio

**Comment by YuriSizov** [comment]
It's working for me, redirects to the new domain with no problem. Perhaps a temporary cache-related issue?

**Comment by Banderi** [comment]
> It's working for me, redirects to the new domain with no problem. Perhaps a temporary cache-related issue?

Can confirm, it's no longer erroring on my end!

**Comment by coppolaemilio** [comment]
It seems like some users were having problems when I removed the content on the `/qa` directory, but a little update to the .htaccess was enough to fix the issue. Sorry about that and thanks for reporting it!
