### ISSUE TITLE
4.1.1 release missing from TuxFamily

### ISSUE THREAD

**Issue by snoopdouglas** [godotengine/godot-website#681]
Hi, I guess this is only technically related to the website - sorry if I'm opening it in the wrong place.

I've noticed that 4.1.1 (and its RC) are both missing from the TuxFamily downloads repository. Is this intentional? I couldn't find any issues mentioning this here or on the engine repo.

**Comment by YuriSizov** [comment]
TuxFamily has been down since the 9th. While downloads worked, we couldn't upload new files to the servers. We are currently moving away from TF to use GitHub as the main download repo (we already do for stable releases). All new pre-release builds are going to be accessible via https://github.com/godotengine/godot-builds. All stable builds are accessible via the main repository, https://github.com/godotengine/godot.

TuxFamily is up at the moment, came back online a few hours ago. So given the opportunity I've uploaded all 3 missing releases to the platform (still synching up). But going forward we'll completely deprecate it.
