### ISSUE TITLE
Proposal - Replace Padlock/Shopping Basket with text link to Asset Lib.

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot-website#74]
https://github.com/godotengine/godot-website/blob/7ad427d60a678c3e4fe75ec58ea62073afca18a0/themes/godotengine/partials/header.htm#L28

Honestly. Neither a Padlock, Nor a shopping basket are intuitive. What are we protecting? What are we selling/buying? It took me until yesterday, since the creation of the asset lib, to realize that that is what the icon is for. I usually just google it.

Placing it next to the Donation button is also confusing. Imho it should sit next to Community, before More.

**Comment by MHillier98** [comment]
Agreed, however fully labeling it as "Asset Library" does take up a lot of space:
![image](https://user-images.githubusercontent.com/26564949/54483848-fdbc5b80-48ae-11e9-9d20-9ca7c9e4d088.png)


However, godotengine/godot-design/issues/17 does have some discussion about there, and there was the suggestion of simply labeling it "Assets"

**Comment by MHillier98** [comment]
Just to get some more discussion:

Because icons don't currently exist on the header, it is probably required to commit to either turning that icon to text, or the "Download" and "Learn" labels to icons to make it more consistent.

Here's what I feel like would be the best solution - to just label it as just "Assets" instead, which makes it clearer for all users.

![image](https://user-images.githubusercontent.com/26564949/84345706-6220b480-abf1-11ea-91be-73923dc80e0e.png)

**Comment by Calinou** [comment]
@MHillier98 Indeed, I think replacing the icon with "Assets" makes the most sense.
