### ISSUE TITLE
Add Moonwards logo as Gold sponsor on homepage

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#96]
[Moonwards](https://www.moonwards.com/) is a Gold sponsor since Sep 1, so their logo and a link to the website should be added to the homepage next to Gamblify's.

I tried to do it a week ago before going on holidays, but it looked bad due to our current CSS not being forgiving for their logo's aspect ratio.

SVG: https://www.moonwards.com/img/MoonwardsLogo2018.svg

So we need to tweak the CSS to better handle this kind of logo.

CC @Calinou @bojidar-bg @mrzapp.

Note that I'm on holidays, so feel free to handle merging a PR and updating the live website without me. Just be careful about the current git diff on the live instance due to the disabled Patreon module for php5 back compat.

**Comment by mrzapp** [comment]
The problem is that they've added a margin around their logo, which the other 2 sponsors haven't, so the "base-padding" class cripples it a bit:

![image](https://user-images.githubusercontent.com/2747428/64821343-e4bd0a80-d5b2-11e9-8cf4-af4274db0afd.png)

Here's the same element without the "base-padding" class:

![image](https://user-images.githubusercontent.com/2747428/64821298-c8b96900-d5b2-11e9-9239-eabecec6b1c7.png)

This can be added to the home.htm layout like this:

![image](https://user-images.githubusercontent.com/2747428/64821626-8f352d80-d5b3-11e9-9556-df0d15f90818.png)

How do you guys usually do this? I'm a bit short on time currently, but I can make a pull request if no one else picks this up.
